export const pokemonTypeToColor = {
    normal: 'blue',
    fire: 'crimson',
    water: 'lightblue',
    electric: 'yellow',
    grass: 'green',
    ice: 'lightskyblue',
    fighting: 'red',
    poison: 'darkolivegreen',
    ground: 'brown',
    flying: 'lightskyblue',
    psychic: 'purple',
    bug: 'darkgreen',
    rock: 'grey',
    ghost: 'grey',
    dragon: 'orange',
    dark: 'black',
    steel: 'slategrey',
    fairy: 'mediumpurple',
};
